"""Python translation of the `programs/zk-token-proof` crate."""

CLOSE_CONTEXT_STATE_COMPUTE_UNITS = 3_300
VERIFY_ZERO_BALANCE_COMPUTE_UNITS = 6_000
VERIFY_WITHDRAW_COMPUTE_UNITS = 110_000
VERIFY_CIPHERTEXT_CIPHERTEXT_EQUALITY_COMPUTE_UNITS = 8_000
VERIFY_TRANSFER_COMPUTE_UNITS = 219_000
VERIFY_TRANSFER_WITH_FEE_COMPUTE_UNITS = 407_000
VERIFY_PUBKEY_VALIDITY_COMPUTE_UNITS = 2_600
VERIFY_RANGE_PROOF_U64_COMPUTE_UNITS = 105_000
VERIFY_BATCHED_RANGE_PROOF_U64_COMPUTE_UNITS = 111_000
VERIFY_BATCHED_RANGE_PROOF_U128_COMPUTE_UNITS = 200_000
VERIFY_BATCHED_RANGE_PROOF_U256_COMPUTE_UNITS = 368_000
VERIFY_CIPHERTEXT_COMMITMENT_EQUALITY_COMPUTE_UNITS = 6_400
VERIFY_GROUPED_CIPHERTEXT_2_HANDLES_VALIDITY_COMPUTE_UNITS = 6_400
VERIFY_BATCHED_GROUPED_CIPHERTEXT_2_HANDLES_VALIDITY_COMPUTE_UNITS = 13_000
VERIFY_FEE_SIGMA_COMPUTE_UNITS = 6_500
VERIFY_GROUPED_CIPHERTEXT_3_HANDLES_VALIDITY_COMPUTE_UNITS = 8_100
VERIFY_BATCHED_GROUPED_CIPHERTEXT_3_HANDLES_VALIDITY_COMPUTE_UNITS = 16_400


def process_proof(instruction: bytes) -> None:
    """Placeholder function to process zk-token proofs."""
    pass
